name: .NET Core

on: 
  push:
    branches:
      - master
  schedule:
    - cron: '0 6 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Run with dotnet
      run: dotnet run --configuration Release
    - name: Upload plot
      uses: actions/upload-artifact@v1
      with:
        name: plot
        path: plot.png
    - name: Publish plot
      run: |
        sudo mkdir /mnt/${{ secrets.azureUser }}
        sudo mkdir /etc/smbcredentials
        sudo bash -c 'echo "username=${{ secrets.azureUser }}" >> /etc/smbcredentials/${{ secrets.azureUser }}.cred'
        sudo bash -c 'echo "password=${{ secrets.azurePassword }}" >> /etc/smbcredentials/${{ secrets.azureUser }}.cred'
        sudo chmod 600 /etc/smbcredentials/${{ secrets.azureUser }}.cred
        sudo mount -t cifs //${{ secrets.azureUser }}.file.core.windows.net/coronaplot /mnt/${{ secrets.azureUser }} -o vers=3.0,credentials=/etc/smbcredentials/${{ secrets.azureUser }}.cred,dir_mode=0777,file_mode=0777,serverino
        sudo cp ./plot.png /mnt/${{ secrets.azureUser }}/plot.png
