name: .NET Core

on: 
  push:
    branches:
      - master
  schedule:
    - cron: '0 6 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install AzCopy
      uses: kheiakiyama/install-azcopy-action@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Run with dotnet
      run: dotnet run --configuration Release
    - name: Upload plot
      uses: actions/upload-artifact@v1
      with:
        name: plot
        path: plot.png
    - name: Publish plot
      # https://docs.microsoft.com/de-de/azure/storage/common/storage-ref-azcopy-copy
      # alias azcp=/opt/hostedtoolcache/azcopy/v10/x64/azcopy_linux_amd64_10.3.4/azcopy
      run: |
        /opt/hostedtoolcache/azcopy/v10/x64/azcopy_linux_amd64_10.3.4/azcopy --source 'plot.png' --destination '${{ secrets.azureWebBlob }}/plot.png${{ secrets.azureWebBlobSAS }}' --set-content-type 'image/png' --overwrite
